version: '3'
services:
  app:
    build:
      context: ./
    image: minjae981002/blog-api-app:latest
    ports:
      - '3000:3000'
    env_file: # 수정된 부분
      - .env # .env 파일을 추가
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - '3306:3306'
