services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: minjae981002/blog-api-app:latest
    ports:
      - '3000'
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - blog-net # 추가된 네트워크

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - '3306:3306'
    networks:
      - blog-net # 추가된 네트워크

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/letsencrypt
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - app
    networks:
      - blog-net # 추가된 네트워크

networks:
  blog-net: # 네트워크 정의
