name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/blog-api-app:latest .

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/blog-api-app:latest

      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > keypair.pem
          chmod 600 keypair.pem

      - name: Deploy to EC2
        run: |
          # EC2에 도커 허브 로그인
          ssh -i keypair.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} "sudo docker login -u '${{ secrets.DOCKER_HUB_USERNAME }}' -p '${{ secrets.DOCKER_HUB_PASSWORD }}'"

          # Docker 자원 정리
          ssh -i keypair.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} "sudo docker system prune -a -f"

          # 새로운 이미지를 풀
          ssh -i keypair.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} "sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/blog-api-app:latest"

          # 새로운 컨테이너 실행 (3001 포트 사용)
          ssh -i keypair.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} "
          sudo docker run -d --name app_new -p 3001:3000 --env-file /home/ubuntu/TravelPlan/.env ${{ secrets.DOCKER_HUB_USERNAME }}/blog-api-app:latest
          "

          # 기존 컨테이너 중지 및 제거
          ssh -i keypair.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} "
          CONTAINER_ID=\$(sudo docker ps -q --filter 'name=app');
          if [ -n \"\$CONTAINER_ID\" ]; then
            sudo docker stop \$CONTAINER_ID;  # 기존 컨테이너 중지
            sudo docker rm \$CONTAINER_ID;    # 기존 컨테이너 제거
          fi
          "

          # Nginx 상태 확인 및 설정 파일 확인
          ssh -i keypair.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} "
          if [ -f /etc/nginx/conf.d/default.conf ]; then
          sudo systemctl status nginx;  # Nginx 상태 확인
          echo 'Nginx 설정 파일이 존재합니다.';
          else
          echo 'Nginx 설정 파일이 존재하지 않습니다. 확인이 필요합니다.';
          exit 1;  # 파일이 없으면 파이프라인 중단
          fi
          "


          # 새로운 컨테이너 이름 변경
          ssh -i keypair.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} "
          sudo docker rename app_new app
          "

          # Nginx 설정 다시 변경 (이제 app:3000으로 변경)
          ssh -i keypair.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} "
          sudo sed -i 's/server app_new:3001;/server app:3000;/' /etc/nginx/conf.d/default.conf
          sudo nginx -s reload
          "
