name: CI/CD Pipeline

# main 브랜치에 push or pr을 하게 되면 CI/CD 실행
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

        # 노드 버전
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

          # npm 다운
      - name: Install dependencies
        run: npm install

        # 도커 이미지
      - name: Build Docker image
        run: docker build -t blog-api-app:latest -f deveops-project/Dockerfile

      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > keypair.pem
          chmod 600 keypair.pem

      - name: Deploy to EC2
        run: |
          ssh -i keypair.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_IP }} "docker pull blog-api-app:latest || true"
          ssh -i keypair.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_IP }} "docker stop $(docker ps -q --filter ancestor=blog-api-app:latest) || true"
          ssh -i keypair.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_IP }} "docker run -d -p 3000:3000 blog-api-app:latest"
