name: CI/CD Pipeline

# main 브랜치에 push or pr을 하게 되면 CI/CD 실행
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

        # 노드 버전
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

          # npm 다운
      - name: Install dependencies
        run: npm install

        # 도커 이미지
      - name: Build Docker image
        run: docker build -t blog-api-app:latest .

      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > keypair.pem
          chmod 600 keypair.pem

      - name: Check EC2 IP
        run: echo "EC2_IP is set" # This won't show the actual IP but confirms it's being referenced

      - name: Deploy to EC2
        run: |
          echo "Length of EC2_SSH_KEY: ${#EC2_IP}"
        # Proceed with the deployment steps

      - name: Deploy to EC2
        run: |
          scp -i keypair.pem -o StrictHostKeyChecking=no ./docker-image ec2-user@${{ secrets.EC2_IP }}:/home/ec2-user
          ssh -i keypair.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_IP }} "docker run -d -p 3000:3000 blog-api-app:latest"
